spring:
  application:
    name: eurekaserver
server:
  port: 8081
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: false