server:
  port: 8082
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
spring:
  application:
    name: cloudprovider
  datasource:
    url: jdbc:mysql://localhost:3306/1805?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      max-wait: 60000
    initialSize: 1
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka