server:
  port: 8084
spring:
  application:
    name: cloudfeign
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka